config/routes.rb
Rails.application.routes.draw do

get "/tasks", to: "tasks#index"
get "/tasks/new", to: "tasks#new"
get "/tasks/:id", to: "tasks#show", as: :task
post "/tasks", to: "tasks#create"
get "/tasks/:id/edit", to: "tasks#edit", as: :edit
patch "/tasks/:id", to: "tasks#update"
delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  #je rajoute du code

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="form">
    <div class="form-title">
      <h1>New Task</h1>
    </div>
    <div class="simple_form">
      <%= simple_form_for @task do |f| %>
        <%= f.input :title %>
        <%= f.input :details %>
        <%= f.input :completed, as: :boolean%>
        <%= f.submit %>
      <% end %>
    </div>
    <%= link_to "back to list", tasks_path %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>My Taks</h1>
<div class="container">
  <ul class="unorded-list">
    <% @tasks.each do |task| %>
    <li class="single-task"> <%= link_to task.title, task_path(task) %> </li>
    <%= link_to "Delete this task", task_path(task), method: :delete, data: { confirm: "are you sure you want to delete"} %>
    <% end  %>
  </ul>
  <%= link_to "add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="form">
    <div class="form-title">
      <h1>New Task</h1>
    </div>
    <div class="simple_form">
      <%= simple_form_for @task do |f| %>
        <%= f.input :title %>
        <%= f.input :details %>
        <%= f.submit %>
      <% end %>
    </div>
    <%= link_to "back to list", tasks_path %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="title">
    <h2> <%= @task.title %></h2>
  </div>
  </div class="details">
    <p><%= @task.details %></p>
    <p><%= @task.completed %></p>

  <div>
  <%= link_to "Back to list", tasks_path %>
  <%= link_to "Edit this task", edit_path %>
</div>